services:
#    lsi_market.example:
#        class: LSI\MarketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    lsi_market.email.civilink_mailer:
        class: LSI\MarketBundle\Email\EnvoyerMail
        arguments:
            - "@mailer"
            - "%mailer_user%"

    LSIMarketBundle\Form\Extension\ImageExtension:
       tags:
           - { name: form.type_extension_type: Symfony\Component\Form\Extension\Core\Type\FileType }