<?php

namespace LSI\MarketBundle\Repository;

/**
 * AdministreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifEpciRepository extends \Doctrine\ORM\EntityRepository
{
}
